name: Check for new BluBank APKs
on:
  workflow_dispatch:
  schedule:
  - cron: "30 20 * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Required Modules
        run: |
            pip install requests 
            pip install BeautifulSoup4

      - name: Execute Script
        run: |
            python main.py
          
      - name: Add APK to archive
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: archive
          FOLDER: downloads
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_EMPTY_COMMITS: true
