name: Check for new BluBank APKs
on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Required Modules
        run: |
            pip install requests 
            pip install BeautifulSoup4

      - name: Execute Script
        run: |
            python main.py
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./*.apk
      
